#!/usr/bin/env bash 

REPODIR=~/zz/sqlcipher 
HOMEDIR=$(pwd) 

cd $REPODIR 

./configure --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC" LDFLAGS="-lcrypto" 

make 

echo "Copying sqlcipher to $HOMEDIR/TEST/enc"
cp sqlcipher $HOMEDIR/TEST/enc
